.TH ANOTE 1 anote\-VERSION
.SH NAME
anote \- take notes or (anote suas coisas)
.SH SYNOPSIS
.B anote
.RB [ \-a [ \-t ] [ \-p ] ]
.RB [ \-d ]
.RB [ \-i FILE ]
.RB [ \-h ]
.RB [ \-l [ TAG ] ]
.RB [ \-r ]
.SH DESCRIPTION
.SH OPTIONS
.TP
.B \-a NOTE
add a note noninteractively.
.B \-l [ \-t TAG] [ \-d ]
list all notes
.SH USAGE
